/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Stefan Bischof (bipolis.org) - initial
 */
package org.eclipse.daanse.dax.unparser.formatted;

import static org.assertj.core.api.Assertions.assertThat;

import java.lang.annotation.Annotation;

import org.eclipse.daanse.dax.model.api.DaxStatement;
import org.eclipse.daanse.dax.parser.api.DaxParserException;
import org.eclipse.daanse.dax.parser.api.DaxParserProvider;
import org.eclipse.daanse.dax.parser.ccc.CCCDaxParserProvider;
import org.eclipse.daanse.dax.unparser.simple.SimpleUnparser;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Round-trip test: the formatted output - with and without comments - must
 * parse again into the same model. Models are compared through their
 * {@link SimpleUnparser} rendering.
 * <p>
 * Plain surefire test; {@code tests.bnd} keeps the (unexported) parser
 * packages out of the OSGi test fragment's imports.
 * </p>
 */
class RoundTripTest {

    private final DaxParserProvider parserProvider = new CCCDaxParserProvider();
    private final SimpleUnparser simple = new SimpleUnparser();

    private DaxStatement parse(String dax) throws DaxParserException {
        return parserProvider.newParser(dax).parseDaxStatement();
    }

    private static FormattedUnparser formatted(boolean includeComments) {
        FormattedUnparser unparser = new FormattedUnparser();
        unparser.activate(new FormattedUnparser.Config() {

            @Override
            public Class<? extends Annotation> annotationType() {
                return FormattedUnparser.Config.class;
            }

            @Override
            public boolean includeComments() {
                return includeComments;
            }

            @Override
            public int indentSize() {
                return 4;
            }
        });
        return unparser;
    }

    @ParameterizedTest
    @ValueSource(strings = { //
            "EVALUATE 'Sales'", //
            "EVALUATE FILTER('Sales', 'Sales'[Amount] * 2 + 1 > 10)", //
            "EVALUATE {(1, \"a\", true), (2, \"b\", false)}", //
            "EVALUATE ROW(\"x\", \"a -- b // c /* d */\")", //
            "DEFINE MEASURE 'Sales'[A] = 1, MEASURE 'Sales'[B] = \"s\", VAR v = dt\"2024-01-31\", "
                    + "TABLE T = FILTER('Sales', true), COLUMN 'Sales'[C] = 'Sales'[Amount], @P = 5 "
                    + "EVALUATE T EVALUATE 'Sales'[Amount]", //
            "DEFINE VAR x = 1 EVALUATE VAR y = x * 2 RETURN ROW(\"Value\", y)", //
            "EVALUATE 'Sales' ORDER BY 'Sales'[Year] DESC, 'Sales'[Region] START AT (2024, \"EU\")", //
            "EVALUATE 'A' ORDER BY 'A'[X] EVALUATE SUM('B'[Y])" //
    })
    void testFormattedOutputParsesToTheSameModel(String dax) throws Exception {
        String expected = simple.unparseDaxStatement(parse(dax));

        for (boolean includeComments : new boolean[] { true, false }) {
            String formattedText = formatted(includeComments).unparseDaxStatement(parse(dax));

            assertThat(simple.unparseDaxStatement(parse(formattedText)))
                    .as("formatted (comments=%s):%n%s", includeComments, formattedText)
                    .isEqualTo(expected);
        }
    }

    private static final String POWER_BI_QUERY = """
            DEFINE
                VAR __DS0Core = SUMMARIZECOLUMNS(
                    ROLLUPADDISSUBTOTAL('Product'[Line], "IsGrandTotalRowTotal"),
                    ROLLUPADDISSUBTOTAL('Date'[Year], "IsGrandTotalColumnTotal"),
                    "SumAmount", CALCULATE(SUM('Sales'[Amount]), ALLSELECTED('Markets'))
                )
                VAR __DS0PrimaryWindowed = TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'Product'[Line], 1)
                VAR __DS0Intersection = SUMMARIZE(__DS0Core, 'Date'[Year], [IsGrandTotalColumnTotal])
                VAR __DS0BodyLimited = SUBSTITUTEWITHINDEX(__DS0PrimaryWindowed, "ColumnIndex", __DS0Intersection, 'Date'[Year], ASC)
            EVALUATE NATURALLEFTOUTERJOIN(__DS0PrimaryWindowed, __DS0BodyLimited)
            ORDER BY [IsGrandTotalRowTotal] DESC, 'Product'[Line]
            EVALUATE SUMMARIZE(__DS0Intersection, 'Date'[Year])
            ORDER BY 'Date'[Year]
            """;

    @Test
    void testPowerBiQueryWithComments() throws Exception {
        String result = formatted(true).unparseDaxStatement(parse(POWER_BI_QUERY));

        assertThat(result).isEqualTo("""
                // DAX Query
                // Generated by Eclipse Daanse Formatted Unparser

                // DEFINE block - declares measures, tables, columns, and variables
                DEFINE
                    // Variable: __DS0Core
                    VAR __DS0Core = // Function: SUMMARIZECOLUMNS with 4 argument(s)
                    SUMMARIZECOLUMNS(ROLLUPADDISSUBTOTAL('Product'[Line], "IsGrandTotalRowTotal"), ROLLUPADDISSUBTOTAL('Date'[Year], "IsGrandTotalColumnTotal"), "SumAmount", CALCULATE(SUM('Sales'[Amount]), ALLSELECTED('Markets')))
                    // Variable: __DS0PrimaryWindowed
                    VAR __DS0PrimaryWindowed = // Function: TOPN with 6 argument(s)
                    TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'Product'[Line], 1)
                    // Variable: __DS0Intersection
                    VAR __DS0Intersection = // Function: SUMMARIZE with 3 argument(s)
                    SUMMARIZE(__DS0Core, 'Date'[Year], [IsGrandTotalColumnTotal])
                    // Variable: __DS0BodyLimited
                    VAR __DS0BodyLimited = // Function: SUBSTITUTEWITHINDEX with 5 argument(s)
                    SUBSTITUTEWITHINDEX(__DS0PrimaryWindowed, "ColumnIndex", __DS0Intersection, 'Date'[Year], ASC)

                // EVALUATE statement - returns the result table
                EVALUATE
                    // Function: NATURALLEFTOUTERJOIN with 2 argument(s)
                    NATURALLEFTOUTERJOIN(__DS0PrimaryWindowed, __DS0BodyLimited)
                // Sort order specification
                ORDER BY [IsGrandTotalRowTotal] DESC,
                    'Product'[Line] ASC
                // EVALUATE statement - returns the result table
                EVALUATE
                    // Function: SUMMARIZE with 2 argument(s)
                    SUMMARIZE(__DS0Intersection, 'Date'[Year])
                // Sort order specification
                ORDER BY 'Date'[Year] ASC""");
    }

    @Test
    void testPowerBiQueryParsesToTheSameModel() throws Exception {
        String expected = simple.unparseDaxStatement(parse(POWER_BI_QUERY));

        for (boolean includeComments : new boolean[] { true, false }) {
            String formattedText = formatted(includeComments).unparseDaxStatement(parse(POWER_BI_QUERY));

            assertThat(simple.unparseDaxStatement(parse(formattedText)))
                    .as("formatted (comments=%s):%n%s", includeComments, formattedText)
                    .isEqualTo(expected);
        }
    }
}
